// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamApiClient is the client API for StreamApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamApiClient interface {
	Add(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type streamApiClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamApiClient(cc grpc.ClientConnInterface) StreamApiClient {
	return &streamApiClient{cc}
}

func (c *streamApiClient) Add(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/api.StreamApi/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamApiServer is the server API for StreamApi service.
// All implementations must embed UnimplementedStreamApiServer
// for forward compatibility
type StreamApiServer interface {
	Add(context.Context, *Req) (*Resp, error)
	mustEmbedUnimplementedStreamApiServer()
}

// UnimplementedStreamApiServer must be embedded to have forward compatible implementations.
type UnimplementedStreamApiServer struct {
}

func (UnimplementedStreamApiServer) Add(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedStreamApiServer) mustEmbedUnimplementedStreamApiServer() {}

// UnsafeStreamApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamApiServer will
// result in compilation errors.
type UnsafeStreamApiServer interface {
	mustEmbedUnimplementedStreamApiServer()
}

func RegisterStreamApiServer(s grpc.ServiceRegistrar, srv StreamApiServer) {
	s.RegisterService(&StreamApi_ServiceDesc, srv)
}

func _StreamApi_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamApiServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StreamApi/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamApiServer).Add(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamApi_ServiceDesc is the grpc.ServiceDesc for StreamApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.StreamApi",
	HandlerType: (*StreamApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _StreamApi_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
